### PR TITLE
Adds support for rebasing releases

### PR DESCRIPTION
**Pull request by bonzofenix**

### CODE REVIEW

**Comment by roxtar** [comment]
+1

**Comment by wfernandes** [comment]
+1

**Comment by bonzofenix** [comment]
I found an issue yesterday with this PR. It tries to rebase all the releases. It still worth merging imo but it limits you to 1 release. There is no easy way to identify which release to rebase without unpacking the tgz in the put step of the resource and checking against a config such as `rebase_releases: [foo-release]` for example

**Comment by vito** [comment]
Sorry for the radio silence, but I don't think we'll be merging this.

Using `--rebase` goes against the design patterns that Concourse pipelines (and this resource) encourage. It makes it so you don't know what you're deploying until you've already introduced a side-effect. It's also not idempotent; it will fail if there are no changes to rebase.

Instead you should just have explicitly versioned dev releases. This can either be done with semver release candidates or, if there's no proper versioning yet, just by creating dev releases with a unix timestamp or something (e.g. `0.0.0-dev.1450057142`).

`--rebase` also makes it hard to guarantee that the release that's been uploaded is the one that will be deployed, or has already been deployed. Today this resource guarantees that by modifying the manifest in-place to specify the version number for each release, which is extracted from the tarball. Using `--rebase` will cause that number to be different once it's uploaded, so the end result would be that the resource guarantees that it *doesn't* deploy what was rebased. :)

Sorry again for the delay; this one slipped through the cracks.

**Comment by jasonkeene** [comment]
+1

**Pull request closed without merging**
